apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-app
  labels:
  {{- template "mytemplate.labels" . }}
spec:
  replicas: 2
  selector:
    matchLabels:
    {{- include "mytemplate.labels" . | indent 2 }}
  template:
    metadata:
      labels:
      {{- include "mytemplate.labels" . | indent 4 }} 
    spec:
      containers:
      - name: sampleapp
        image: lerndevops/samples:unapp
        ports:
        - containerPort: 80
