{{/* Common Labels */}}
{{- define "nt1.labels"}}
    app: sapp
    cname: {{ .Chart.Name }}
{{- end }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-app
  labels:
  {{- template "nt1.labels" . }}
spec:
  replicas: 2
  selector:
    matchLabels:
    {{- include "nt1.labels" . | indent 2 }}
  template:
    metadata:
      labels:
      {{- include "nt1.labels" . | indent 4 }} 
    spec:
      containers:
      - name: sampleapp
        image: lerndevops/samples:unapp
        ports:
        - containerPort: 80
