{{/* Common Labels */}}
{{- define "mytemplate"}}
    app: sapp
{{- end }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-app
  labels:
  {{- template "mytemplate" }}
spec:
  replicas: 2
  selector:
    matchLabels:
    {{- include "mytemplate" . | indent 2 }}
  template:
    metadata:
      labels:
      {{- include "mytemplate" . | indent 4 }} 
    spec:
      containers:
      - name: sampleapp
        image: lerndevops/samples:pyapp-v1
        ports:
        - containerPort: 3000
