apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-service
spec:
  type: {{ .Values.servicetype }}
  ports:
   - port: {{ .Values.ports.serviceport }}
     targetPort: {{ .Values.ports.containerport }}
  selector:
    app: myapp
