apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  labels:
    app: nginx
spec:
  replicas: {{ .Values.replicas }}
  selector:
    {{- with .Values.rlabels }}
    matchLabels:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  template:
    metadata:
      {{- with .Values.rlabels }}
      labels:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      containers:
      - name: nginx
        image: {{ .Values.image.repo }}:{{ .Values.image.tag }}
        ports:
        - containerPort: 3000
